name: Build and publish Leda Prod

on:
  push:
    tags:
      - 'v*'

jobs:
  build_and_push:
    environment: LEDA_API_PROD
    runs-on: ubuntu-latest
    steps:
      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Use tag
        run: echo ${{steps.tag.outputs.tag}}
      - name: Build image
        run: docker build -t ledaapi .
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Log in to DO Container Registry
        run: doctl registry login --expiry-seconds 600
      - name: Tag image
        run: docker tag ledaapi registry.digitalocean.com/metis/ledaapi:${{ steps.tag.outputs.tag }}
      - name: Push image to DO Container Registry
        run: docker push registry.digitalocean.com/metis/ledaapi:${{ steps.tag.outputs.tag }}
      - name: Install dependencies
        run: yarn install
      - name: Run database migrations
        run: yarn run migration:run
        env:
          DB_TYPE: ${{secrets.DB_TYPE}}
          DB_HOST: ${{secrets.DB_HOST}}
          DB_PORT: ${{secrets.DB_PORT}}
          DB_USERNAME: ${{secrets.DB_USERNAME}}
          DB_PASSWORD: ${{secrets.DB_PASSWORD}}
          DB_NAME: ${{secrets.DB_NAME}}
